server:
  shutdown: graceful
  port: 8761

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://172.17.0.1:8761/eureka/
  server:
    enable-self-preservation: true

logging:
  level:
    com.example.discovery: INFO
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: INFO
    org.hibernate.orm.jdbc.extract: INFO
    org.springframework.transaction.interceptor: INFO